
# netlify.toml
# This file configures your Netlify deployment

[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command with explicit dependency installation and npx for running vite
  command = "npm ci && npm install vite@5.4.10 @vitejs/plugin-react-swc && npx vite build"
  # Base directory (where your package.json is located)
  base = "/"

# Branch settings (default to 'main' if not specified in UI)
[context.production]
  branch = "main"

# Set environment variables needed for build
[build.environment]
  # Tell Vite we're building for production
  NODE_ENV = "production"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
