
# netlify.toml
# This file configures your Netlify deployment

[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command with explicit dependency installation and ignoring warnings
  command = "CI=false npm ci && npm run build"
  # Base directory (where your package.json is located)
  base = "/"

# Branch settings (default to 'main' if not specified in UI)
[context.production]
  branch = "main"

# Set environment variables needed for build
[build.environment]
  # Tell Vite we're building for production
  NODE_ENV = "production"
  # Specify Node version to avoid compatibility issues
  NODE_VERSION = "18"
  # Setting CI to false directly in the environment (belt and suspenders approach)
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
