
# netlify.toml
# This file configures your Netlify deployment

[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command that explicitly installs vite and its dependencies before building
  command = "npm ci && npm install vite @vitejs/plugin-react-swc && npx vite build"
  # Base directory (where your package.json is located)
  base = "/"

# Branch settings (default to 'main' if not specified in UI)
[context.production]
  branch = "main"

# Set environment variables needed for build
[build.environment]
  # Tell Vite we're building for production
  NODE_ENV = "production"
  # Specify Node version to avoid compatibility issues
  NODE_VERSION = "18"
  # Setting CI to false to prevent treating warnings as errors
  CI = "false"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force a new deploy by adding this comment - Build trigger: 3

