
# netlify.toml
# This file configures your Netlify deployment

[build]
  # Directory to publish (output of the build)
  publish = "dist"
  # Build command with explicit dependency installation and ensuring vite is available
  command = "npm ci && npm i -g vite && npm run build"
  # Base directory (where your package.json is located)
  base = "/"

# Branch settings (default to 'main' if not specified in UI)
[context.production]
  branch = "main"

# Set environment variables needed for build
[build.environment]
  # Tell React we're building for production
  NODE_ENV = "production"
  # Specify Node version to avoid compatibility issues
  NODE_VERSION = "18"
  # Setting CI to false to prevent treating warnings as errors
  CI = "false"
  # Ensure Vite picks up environment variables
  VITE_SUPABASE_URL = "https://phdxahmpqvobbrqqjbut.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZHhhaG1wcXZvYmJycXFqYnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3MzAyODgsImV4cCI6MjA1MjMwNjI4OH0.lVWfcAaigt8z5yskV8XLH_EhYJJiNQ9mz_5PTQKMBng"

# Configure post-processing of build assets 
[build.processing]
  skip_processing = false

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force a new deploy by adding this comment - Build trigger: 13
